name: Deploy Changed Workers

on:
  push:
    branches: [main]
    paths:
      - "workers/**"
      - "wrangler.template.toml"

jobs:
  migrate:
    name: Run Migrations
    runs-on: ubuntu-latest
    needs: detect
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: node .github/workflows/migrate.js
      
  detect:
    name: Detect changed workers
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set.outputs.matrix }}
      has_changes: ${{ steps.set.outputs.has_changes }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Detect changed workers
        id: set
        run: |
          changed=$(git diff --name-only HEAD^ HEAD | grep '^workers/' | cut -d '/' -f2 | sort -u)
          if [ -z "$changed" ]; then
            echo "No changed workers."
            echo "matrix={\"worker\":[]}" >> $GITHUB_OUTPUT
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            matrix=$(echo "$changed" | jq -R -s -c 'split("\n") | map(select(length > 0))')
            echo "Changed workers: $matrix"
            echo "matrix={\"worker\":$matrix}" >> $GITHUB_OUTPUT
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

  deploy:
    name: Deploy ${{ matrix.worker }}
    needs: detect
    if: needs.detect.outputs.has_changes == 'true'
    runs-on: ubuntu-latest
    environment: private1
    strategy:
      matrix: ${{ fromJson(needs.detect.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm install
        
      - name: Deploy worker
        run: .github/workflows/_deploy-worker.sh
        env:
          WORKER_NAME: ${{ matrix.worker }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          ZONE_NAME: ${{ secrets.ZONE_NAME }}
