name: Deploy Changed Workers

on:
  push:
    branches: [main]
    paths:
      - "workers/**"
      - "wrangler.template.toml"

jobs:
  detect:
    name: Detect changed workers
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Detect changes
        id: set
        run: |
          changed=$(git diff --name-only HEAD^ HEAD | grep '^workers/' | cut -d '/' -f2 | sort -u | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "matrix={\"worker\":$changed}" >> $GITHUB_OUTPUT

  deploy:
    name: Deploy ${{ matrix.worker }}
    needs: detect
    if: fromJson(needs.detect.outputs.matrix).worker != []
    runs-on: ubuntu-latest
    environment: private1
    strategy:
      matrix: ${{ fromJson(needs.detect.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm install

      - name: Deploy worker
        run: .github/workflows/_deploy-worker.sh
        env:
          WORKER_NAME: ${{ matrix.worker }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
