name: Deploy Selected Workers

on:
  workflow_dispatch:
    inputs:
      workers:
        description: 'Comma-separated list of workers to deploy'
        required: true

jobs:
  deploy:
    name: Deploy ${{ matrix.worker }}
    runs-on: ubuntu-latest
    environment: private1
    strategy:
      matrix:
        worker: ${{ fromJson('["' + github.event.inputs.workers.replace(',','","') + '"]') }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm install

      - name: Run D1 Migrations
        run: node .github/workflows/migrate.js

      - name: Deploy worker
        run: .github/workflows/_deploy-worker.sh
        env:
          WORKER_NAME: ${{ matrix.worker }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          ZONE_NAME: ${{ secrets.ZONE_NAME }}
